### ISSUE TITLE
Question: are you planning to release the code under an open license?

### ISSUE THREAD

**Issue by ivan-marroquin** [BayesWatch/deep-kernel-transfer#12]
Hi,

Many thanks for making this code available. I was wondering if you are going to release it under an  open license?

Kind regards,

Ivan

**Comment by mpatacchiola** [comment]
Hi @ivan-marroquin 

Things are complicated since our code is partially based on a fork. You can find the original license here:

https://github.com/wyharveychen/CloserLookFewShot/blob/master/LICENSE.txt

From our side we are happy to give permission for the use of our code. However, the use must complies with the specified conditions of the original license from the fork. Note that the original license is not a standard one. We are not lawyers, and so we do not give any undertaking as to what else it does or does not enable. We suggest to contact the authors of the original license and ask for clarifications and/or permissions if you need to.

**Comment by ivan-marroquin** [comment]
Hi @mpatacchiola ,

Many thanks for the quick reply! I will contact the author of the original code.

Ivan

**Comment by ivan-marroquin** [comment]
Hi @mpatacchiola,

I looked at the code and license by the developers of https://github.com/wyharveychen/CloserLookFewShot

It seems to me that the license may only affect the code that you developed for classification and regression on images. But, the code developed for regression on tabular data (using Gaussian processes) is not attached to the license. Am I correct? 

Since I am only interested in the code based on Gaussian processes for regression, this code could be released under an open license?

Kind regards,

Ivan

**Comment by mpatacchiola** [comment]
Hi @ivan-marroquin 

I think you may be right. The code for the regression case contained in the folder [/sines](https://github.com/BayesWatch/deep-kernel-transfer/tree/master/sines) is standalone and does not depend on the rest of the code. In principle this could be released with a different license and we would be happy to use an open one.

However, we still need to figure out which license would be the most appropriate.

**Comment by ivan-marroquin** [comment]
Hi @mpatacchiola ,

That sounds perfect! I close the incident and thanks for taking into consideration my request.

Ivan
