### ISSUE TITLE
Multi GPU Training

### ISSUE THREAD

**Issue by surtantheta** [BayesWatch/deep-kernel-transfer#7]
Can you provide the code or let me know how we can include Multi GPU for training this model? Due to ResNet + GP structure, I am unable to directly implement that.

**Comment by mpatacchiola** [comment]
Hi @surtantheta 

Our code does not implement the multi GPU at the moment, mainly because of the limits in the parallelization of the GP in GPytorch.

However, recent versions of GPytorch support multi GPU. Give a look at [this example](https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.ipynb). It seems that you just need to use `gpytorch.kernels.MultiDeviceKernel()` to spread the kernel over multiple devices.
